#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080 

# check for needed vars (todo: add check for more params?)

if [[ -z $OPENSHIFT_DIY_LOG_DIR ]]; then
	echo "$(date) [ERROR]: OPENSHIFT_DIY_LOG_DIR not defined"
	exit 1
fi

LOG_FILE="${OPENSHIFT_DIY_LOG_DIR}play.log"

# figure out the start script (and ensure it is runnable)

START_SCRIPT_BAT=`find ${OPENSHIFT_REPO_DIR}target/universal/stage/bin -name \*.bat`

START_SCRIPT=${START_SCRIPT_BAT%.bat}

chmod +x $START_SCRIPT

# start application

APP_COMMAND="$START_SCRIPT $PLAY_PARAMS "\
"-Dhttp.port=${OPENSHIFT_DIY_PORT} "\
"-Dhttp.address=${OPENSHIFT_DIY_IP} "\
"-Dconfig.resource=openshift.conf"

echo "$(date) [INFO]: Starting: $APP_COMMAND" &>> $LOG_FILE
nohup bash -c "${APP_COMMAND} &>> ${LOG_FILE} 2>&1" &> /dev/null &
